# Basic
title: Three Cai
subtitle: 让人迷茫的原因只有一个——那就是本该拼搏的年纪，却想得太多，做得太少！
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
welcome_message: 
description: Hello，大家好，我叫徐三才，iOS工程师一枚。
creator: <a href="https://www.xusancai.com">@xusancai</a>

# url: "http://vno.onevcat.com"
url: "https://www.xusancai.com"
enforce_ssl: xusancai.com

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/sancaixu'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: sancaixu
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: sancaixu
    # twitter: SANCAIXU
    # gplus: 107108267983477358170
    mail: sancaixu@163.com

# Google Analytics
ga:
    id: UA-81174961-1
    host: xusancai.com
